### ISSUE TITLE
Python example

### ISSUE THREAD

**Issue by uod-jhardy** [ndejong/digital-multimeter#9]
Excellent software using cli but could you add a very simple Python example showing how to take single or multiple readings. I am trying to follow the limited python documentation but I am missing something...

**Comment by ndejong** [comment]
Yes, fair point we don't have any Python examples explicitly documented, it's burred in the CLI code.

Either way, you should be able to do something like this

```python

from digital_multimeter.main import DigitalMultimeter

dmm = DigitalMultimeter(connect="/dev/ttyUSB0", model="MultimeterEDI9604")
reading = dmm..get_reading()
print(reading)

```

**Comment by uod-jhardy** [comment]
Thanks for this, I was missing the .main. This is exactly the sort of simple example that I was looking for, just a starting point. I am sure that others will benefit as well.
